### ISSUE TITLE
swupd-server version

### ISSUE THREAD

**Issue by aaronovz1** [pohly/meta-swupd#2]
I assume the bump to 3.6.X is waiting on the libarchive patches to be integrated so you don't need to rebase the current patch set?

**Comment by pohly** [comment]
I have rebased locally and just not pushed to the branch yet. I was told that there have been format changes, which means that I need to bump that. I'll get to it eventually.

**Comment by aaronovz1** [comment]
Ok. Thanks for the update!

**Comment by aaronovz1** [comment]
Noticed you updated to 3.6.2. I'll close this out. Thanks
