### ISSUE TITLE
systemctl not found

### ISSUE THREAD

**Issue by aaronovz1** [pohly/meta-swupd#5]
I am seeing errors after running an update saying that _/usr/bin/systemctl_ is not found. I think the issue is because the path used in the "fix_paths" patch function is specifying the wrong directory.

I think it should be using "${base_prefix}/bin" instead of "{bindir}". The latter points to "/usr/bin" which is what the fix is trying to resolve.

**Comment by pohly** [comment]
Good point, I'll fix this.

**Comment by aaronovz1** [comment]
Looks like this fix hasn't made it in yet? Just checking it wasn't forgotten
